variables:
  GIT_STRATEGY: none

stages:
  - Build

LTS-v13_AST2600EVB_FULL1:
  stage: Build
  image:
    name: amispx:v0.1
  tags:
    - "LTS-Build"
  retry:
    max: 2
    when:
      - runner_system_failure
      - job_execution_timeout
      - scheduler_failure
  script:
    - export Branch=LTS-v13
    - export CIOutput=$(pwd)/${CI_JOB_STAGE}_Output/${CI_JOB_NAME}    
    - git clone https://git.ami.com/core/rd/active-tree/LTS /tmp/LTS        
    - cat /tmp/LTS/script/LTS-v13_AST2600EVB_FULL1.sh
    - cd /tmp/LTS/script
    - source ./LTS-v13_AST2600EVB_FULL1.sh

  artifacts:
    paths:
    - ${CI_JOB_STAGE}_Output/${CI_JOB_NAME}
    expire_in: 12 weeks
  only:
  - branches
  except:
  - master
